<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UrDeck.Core\UrDeck.Core.csproj" />
    <ProjectReference Include="..\..\src\UrDeck.Analyzer\UrDeck.Analyzer.csproj" />
  </ItemGroup>

</Project>
